### ISSUE TITLE
"Disclosure" isn't a valid field name

### ISSUE THREAD

**Issue by joker314** [lirantal/express-security-txt#15]
I may be mistaken, but there doesn't appear to be a `Disclosure: full` listed in the specification. Perhaps this should be removed

**Comment by lirantal** [comment]
@joker314 correct, it was indeed removed quite a while ago.
Would you like to submit a PR or should I go ahead with the fix?

**Comment by joker314** [comment]
I'll submit one

**Comment by lirantal** [comment]
Awesome! I added you as a collaborator to the project

**Comment by joker314** [comment]
Thanks! Should pull requests be based on `feat-update-to-latest-internet-draft-4` or `master`?

**Comment by lirantal** [comment]
Since the RFC is still draft I think we can always work with the latest changes. WDYT?

**Comment by joker314** [comment]
Yeah, I think that makes sense. (just to double check: that means `master`, right?)

**Comment by lirantal** [comment]
Yes we should work with `master` as the source of truth
