### ISSUE TITLE
Content-Type is not text/plain

### ISSUE THREAD

**Issue by joker314** [lirantal/express-security-txt#17]
`security.txt` file should be served over HTTP with a Content-Type of `text/plain`, per the standard.

At the moment, the Content-Type is `text/html`. This makes it hard for a human to read because newlines are gobbled up, and some machines might ignore such a file (thinking it's a 404 page).

The solution is to place a line like:

```
res.header('Content-Type', 'text/plain')
```

Before responding.

**Comment by lirantal** [comment]
Sounds good! Let's fix it.

**Comment by joker314** [comment]
Would you like to do it or shall I?

**Comment by lirantal** [comment]
You're on a roll ;-)
