### ISSUE TITLE
Missing "Permission" directive

### ISSUE THREAD

**Issue by joker314** [lirantal/express-security-txt#21]
In the latest draft, a `Permission:` directive was added -- we should probably support it too.

It must
  - Only appear once (i.e. not be an array)
  - Be set to the string `'none'`

**Comment by lirantal** [comment]
Sounds good. What's the permission directive is used for?
I've been a bit out of sync with the proposal

**Comment by joker314** [comment]
It's used for saying "Don't perform security research on us".

EDIT: per [3.4.5](https://tools.ietf.org/html/draft-foudil-securitytxt-04#section-3.4.5)

**Comment by lirantal** [comment]
Got it. Thanks.
