### ISSUE TITLE
Allow more chaining of directives

### ISSUE THREAD

**Issue by joker314** [lirantal/express-security-txt#22]
`Contact:` is most well known for being allowed to appear multiple times (and then the values are ~~changed~~ __chained__ together). The RFC currently allows some other directives to be chained, too:

#### Can be chained
- Acknowledgements
- Contact
- Encryption
- Hiring
- Policy

#### Cannot be chained
- Signature
- Permission

We could accept arrays (like for `Contact:`) to allow for multiple fields using the same directive type.

**Comment by lirantal** [comment]
When you say allow Encryption or Acknowledgements to be changed you mean there will be several instances of those fields?

If so it indeed makes sense we enable them to be provided as arrays that we can create several instances of.

**Comment by joker314** [comment]
Yeah, precisely!

**Comment by joker314** [comment]
Would a refactor be a good idea here? So, like:

```javascript
const rules = {
  mustExist: ['contact'],
  mustBeString: ['permission', 'signature'],
  moreRules: {
    'permission': value => value.toLowerCase() !== 'none' ? 'must be "none"' : null,
    'encryption': value => value.toLowerCase().startsWith('http:') ? 'must be secure URI' : null
  }
}
```

And then the validator reads from that object to decide whether there's a valid thing passed to it.

**Comment by lirantal** [comment]
Sounds good.
Instead of writing the validations yourself though, I suggest we make use of Joi for the options schema.
