### ISSUE TITLE
Do we need a security.txt file?

### ISSUE THREAD

**Issue by joker314** [lirantal/express-security-txt#28]
Should this repository have a `.security.txt` file at its root, providing contact details to report security vulnerabilities in our project?

There are of course other ways security researchers can contact us about vulnerabilities (e.g. Node.js third-party modules), but a `.security.txt` file could simply point to those ways.

An example of a security issue which we could face: the _Contact:_ directive could be changed by a logical bug, causing reports to go to a non-existent (or possibly existent!) different place.

**Comment by lirantal** [comment]
Yep. What do you think about including [this security template](https://github.com/nodejs/security-wg/blob/master/processes/responsible_disclosure_template.md) from the Security WG and linking it to a badge on the README page like it's on the Sec WG repo?

**Comment by joker314** [comment]
Great! I'll get right on this.
<hr>

It's implied, but is the WG's template for security disclosure licensed under something like CC0?

**Comment by lirantal** [comment]
It's MIT as part of the entire repo. Do you see it as an issue?

**Comment by joker314** [comment]
IANAL
MIT requires that the copyright notice be distributed with the Software (and Software does probably include the file), so would we need to include that copyright notice for this?

If the answer is "no", I'm sure everybody would understand that a template is intended to be used, and understand that the wg is not going to try and sue everybody they can simply because they have the ability to do so.

Based on that logic, I personally don't see it as an issue, but I don't have a strong opinion either way.
