### ISSUE TITLE
How (if at all) should comments be handled?

### ISSUE THREAD

**Issue by joker314** [lirantal/express-security-txt#33]
# Introduction
Comments are pieces of human-readable text intended to clarify a `security.txt` file. The specification reads as follows:

[§ 3.2 - Comments](https://tools.ietf.org/html/draft-foudil-securitytxt-04#section-3.2)
>   You MAY use one or more comments as descriptive text immediately before the field.  Parsers SHOULD associate the comments with the respective field.

We represent security.txt files as key ↔️ value pairs. However, unlike fields (which are directive ↔️ value pairs), comments aren't really pairs of anything, so there isn't a 'perfect' way of representing them.

This issue is for discussion on two things:
- Whether we should implement comments; and if so
- How we should implement comments

All the below examples generate the below security.txt file:
```
# Please let me know about security issues, I don't bite!
Contact: mailto:example@example.com
```

# Method 1: Extra keys

We could allow for one comment per directive type. These key names for the comments could be an underscore followed by the directive.

```
securityTxt.setup({
  _contact: 'Please let me know about security issues, I don't bite!',
  contact: 'mailto:example@example.com',
})
```

This implementation allows the object used to generate the security.txt file read top-to-bottom with a similar structure to the file that will actually be generated. However, it only allows one comment per directive type. What if you want to comment about your email method separately to talking about your telephone method?

Notes:
 - newlines should be handled okay (i.e., add `#`s where needed)
 - arrays should be treated as arrays of lines (i.e., prefix each element with `#`)
 - arrays of strings containing newlines should work

# Method 2: Extra values
For certain directives, we already allow arrays of values. Let's add a 'comment' value that can be an element of such an array.

```
securityTxt.setup({
  contact: [
    securityTxt.comment('Please let me know about security issues, I don't bite!'),
    'mailto:example@example.com'
  ]
})
```

This has the advantage that you can add a field, then a comment, then another field of the same type, then another comment, etc. However, it's super verbose.

Note: `.comment` returns an object representing the comment
# Method 3: New directive syntax
Instead of using an object, we could use an array.
```
securityTxt.setup([
  securityTxt.field(
    'contact',
    'mailto:example@example.com',
    'Please let me know about any security issues, I don't bite!'
  )
])
```

This is quite verbose. We don't need to do a `securityTxt.setup`, we could have `.field` just register each field. However, this has a slight performance drawback, since we have to re-generate the file multiple times (as each new field is generated). Alternatively, we could generate each security.txt file only when it's requested, but cache it after the first time. However, doing this would make the first security researcher have a slightly slower experience. Probably all of this is marginal.

Note: `.field`, if we decide to use it in an array passed to `.setup`, would return an object representing the field.

**Comment by lirantal** [comment]
Wonderfully laid out RFC @joker314, really appreciate putting this out.

What about having a variation of Method 2 where instead of an array, which will require users to remember the positions for each, we will use an object that clearly expresses the intent of each value? This way it will also be easier to extend it in the future and provide each element further metadata if required.

An example:

```js
securityTxt.setup({
  contact: {
    comment: "Please let me know about security issues, I don't bite!",
    value: "mailto:example@example.com"
  }
})
```

* We can also pretty easily manage backwards compatibility by composing the text based on whether a property (i.e: `contact`) is a string or an object.
* Allows for general extension, for example if someone wanted to just put a comment as a prefix, and comment as a suffix, unrelated to each field we can use special metadata fields like `_prefixComment` and `_postfixComment`

BTW this also gives me the notion that the library could grow to be more complex and maybe some users will just want to provide us a hard-coded string for the security.txt.

**Comment by joker314** [comment]
I concur that the API should be backwards compatible, and be able to handle both objects and strings.

Just to check, to produce this file:

```
# I don't check my email as often
Contact: mailto:example@example.com
# Please don't call at night
Contact: tel:+123456789
# Thanks for taking the time to read this file
```

Then one would write:

```
{
  contact: [
    {
      comment: 'I don\'t check my email as often',
      value: 'mailto:example@example.com'
    },
    {
      comment: 'Please don\'t call at night',
      value: 'tel:+1234566789'
    }
  ],
  postfixComment: 'Thank you for taking the time to read this file'
}
```
(and `postfixComment` could also be positioned in the second Contact field to produce the same result).

If so, I concur that this is a beautiful solution; are you interested in doing this? (I'm happy to do it if not)

**Comment by lirantal** [comment]
Looks good.
Would be great if you can work on it, you are doing an amazing job!

**Comment by joker314** [comment]
Hmm, so I started working on this, and while I agree this syntax is easy to extend, I'm not sure how to deal with stuff like
- should `value` be compulsory?
- are you allowed to put an object (comment + value) followed by just a string (value)?

TBH I think the original Method 2 didn't require remembering positions of things: the positions indicated where in the file the comment would go.

Thoughts?

**Comment by lirantal** [comment]
If `value` is not provided then that directive will have no meaning, and that's ok. But on the other hand, it a user might not know about it so I think it's best to throw an error if that happens.

Mixing both strings as well as an objects to the array seems like a bad idea and I wouldn't support that.
I'd say it's either you provide a string for a field, or an object.

IMO we should try to be opinionated and simple as possible, without having to try and support all the possible oddities and different ways to compose it.
