### ISSUE TITLE
Investigate breaking changes in Joi

### ISSUE THREAD

**Issue by joker314** [lirantal/express-security-txt#34]
I didn't notice the breaking changes v14 of Joi introduced. They were documented in an issue -- and I didn't manage to find it.

There may be subtle edge cases (such as arrays of non-strings) which _might_ have changed.

We should investigate.

hapijs/joi#1615

**Comment by lirantal** [comment]
Seems that if everything passes in tests then nothing we should worry about, no?

**Comment by joker314** [comment]
Assuming correct usage, yeah. Should we worry about someone passing a date/number/etc as a field value, though? We don't test for that at the moment.

**Comment by lirantal** [comment]
We can use joi as the schema for input and that's it.
I believe any user would easily just read the docs in the README and the example usage to use the library.

**Comment by joker314** [comment]
Are you talking about joi or express-security-txt?

To be clear, our schema might've been too lax (joi has/had an automatic type coercion feature where if anything _could_ be a string it was considered one) and v14 may have changed the behaviour of our schema, causing a security.txt file like:

```
securityTxt.setup({
  contact: 5
})
```

to break. In this specific case, one might argue that 5 isn't a valid URI, but maybe someone passed an object which -- when cast to a string using its toString method -- gave a valid URI.

Tbh, I would guess our number of users is low enough that nobody did anything wild with our library, and hence such a breaking change would be a non-issue?

**Comment by lirantal** [comment]
>Are you talking about joi or express-security-txt?

I meant that we can joi as a schema to validate input for the setup method usage

If you think the Joi upgrade might have caused issues then we should be semver compatible and release this new version as a new major

**Comment by joker314** [comment]
Well, it's too late: #31 

I don't think a normal user of express-security-txt is affected, though; it's just unexpected behaviour will now throw an error where it didn't before (which is _technically_ a breaking change)

**Comment by lirantal** [comment]
Indeed.
