### ISSUE TITLE
The last line of the file must also be terminated with a newline character

### ISSUE THREAD

**Issue by joker314** [lirantal/express-security-txt#36]
> **[§ 3.3](https://tools.ietf.org/html/draft-foudil-securitytxt-04#section-3.3) Separate Fields**
> Every line MUST end either with a carriage return and line feed characters (CRLF / %x0D %x0A) or just a line feed character (LF / %x0A).

We use the `\n` as a line _seperator_, whereas the specification appears to demand (with a 'MUST') that we use `\n` as a line _terminator_. This means that there should be a `\n` at the end of the last line too.

I found a [StackOverflow question](https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline) asking why people do this. It seems especially important for those reading security.txt files as a stream (and looking for the line terminator to decide when to stop reading for that field); and for those concatenating two security.txt files (e.g. if two companies have merged?).

We do:
https://github.com/lirantal/express-security-txt/blob/7d295f6b8b40a6ef41bda52c4ffacf0aef35da45/index.js#L76

We should change the `'\n'` to `''` and then put the line terminator here:
https://github.com/lirantal/express-security-txt/blob/7d295f6b8b40a6ef41bda52c4ffacf0aef35da45/index.js#L69

<hr>

Notice that we actually have two places where we push fields:
https://github.com/lirantal/express-security-txt/blob/7d295f6b8b40a6ef41bda52c4ffacf0aef35da45/index.js#L69-L72

I would argue that we should convert strings to singleton arrays (`"tel:+123"` => `["tel:+123"]`) and then we wouldn't need to have two different places where we are doing the pushing.

**Comment by lirantal** [comment]
Well put explanation.
So with regard to the changes in PR #37, we aren't really changing the user API to require specifying as an array, but internally convert it to an array if its not. Right?

**Comment by joker314** [comment]
That's right, yeah.

**Comment by lirantal** [comment]
Great. Let's merge then.
