### ISSUE TITLE
Use a loop when constructing the security.txt file

### ISSUE THREAD

**Issue by joker314** [lirantal/express-security-txt#38]
In this set of lines:

https://github.com/lirantal/express-security-txt/blob/f48bfe2a56ce880eeec805a9240a0b354a7113f7/index.js#L41-L63

We could probably make the code shorter/easier to modify if we had an array or object and then looped over it. I'm thinking either we have an object like this, to map our notation to the policy's notation:

```
{
  contact: "Contact",
  encryption: "Encryption",
  ...
}
```

Or, we have an array and a function:

```
function capitalised(text) {
  return "...";
}

const fields = ["contact", "encryption", "..."]
```

We could then modify the existing loop at https://github.com/lirantal/express-security-txt/blob/master/index.js#L66-L74 to go through every known key we support, and capitalise it (either with an object or function) and then check if the value was provided. If it wasn't we drop it _in the loop_

I think this would make adding new properties faster. We could also have the schema validation use our array/object when deciding which policy fields are allowed?

**Comment by lirantal** [comment]
yeah, that makes sense.
