### ISSUE TITLE
Acknowledgement has now been renamed to Acknowledgments

### ISSUE THREAD

**Issue by joker314** [lirantal/express-security-txt#39]
```diff
- Acknowledgement
+ Acknowledgments
            ^   ^
```

We have a missing "e" and an extra "s".

Should we release a breaking change modifying the name of the key in our object? Should we only change the output we generate?

[§ 3.4.1 Acknowledgments](https://tools.ietf.org/html/draft-foudil-securitytxt-04#section-3.4.1)

**Comment by lirantal** [comment]
Good catch!

WDYT about:
1. Keep the current key to not break any existing clients
2. Support additionally a new key that is correctly spelled
3 Update the docs and examples in the README, and any tests to use the new spelling 
4. Output should be changed to use the new one, yes.

**Comment by joker314** [comment]
Perfect, but what do we do if someone specifies both spellings. Should we make both keys at the same time error?

Edit: should we console.warn if we detect use of the old spelling?

**Comment by lirantal** [comment]
The console.warn is a good idea to use incase of the spelling error indeed.
At the moment I'd keep both spellings, later in the future and in a major release we can deprecate the older one. Maybe we can add a `@TODO` in the existing spelling error option so that we remember why it's there.

**Comment by joker314** [comment]
So we should go through this process:

1. Allow either spelling (but not both at the same time), use 'console.warn' for the older one, and add a `@TODO` for future reference
2. In a breaking release (in a ~month?), error when using the older one

**Comment by lirantal** [comment]
Sounds good 👍
