### ISSUE TITLE
Should undefined option values throw a validation error

### ISSUE THREAD

**Issue by joker314** [lirantal/express-security-txt#42]
```
{
  contact: 'test',
  encryption: undefined
}
```

Generates

```
Contact: test
```

Should it instead throw a validation error?

**Comment by lirantal** [comment]
Don't think so.
Do you think there's a case that we should support throwing an error there?

**Comment by joker314** [comment]
I mean, `undefined` isn't a string, array, or comment object 😛. On the other hand, I totally see this use case:

```
{
  contact: getContact(),
  encryption: getEncryption(),
     ... for all keys ...
}
```

Where being able to say "don't include this is important". So I think we agree we shouldn't error and this behaviour is okay.
