### ISSUE TITLE
Fully remove "acknowledgement" as it has been renamed

### ISSUE THREAD

**Issue by joker314** [lirantal/express-security-txt#47]
Due to #39, we decided to deprecate "Acknowledgement" in #45. It's been about a month, and our plan is to release a breaking change which disables the old spelling completely, leading to validation failing if it's used.

I attempted to do this, by setting `DEPRECATIONS` to an empty object. However, I don't know how to get coverage to 100%.

The logic for handling deprecations cannot be tested if there are no deprecations to use for the testing, and yet if we remove that logic, if the RFC changes (as it is still a draft), we'd have to re-add it, which takes some work.

Possible solutions:
 - Keep the field deprecated until the RFC exits draft (when we remove all deprecations and the logic surrounding it)
 - Move `DEPRECATIONS` into a JSON file, as maybe that's easier to mock with jest?
 - Comment out the deprecation logic
 - Ignore the coverage isue

**Comment by lirantal** [comment]
What do you think is best?
I'm ok with keeping the field deprecated until the RFC exits draft.

**Comment by joker314** [comment]
I agree: I think that's probably the least work and probably is a good idea, since it gives people more time to transition to the new spelling.
