### ISSUE TITLE
Use second person in documentation

### ISSUE THREAD

**Issue by joker314** [lirantal/express-security-txt#49]
When writing the documentation for some of the newer features, a lot of fourth person was used ('one should...'). It should be rephrased to use second person ('you should...'), as it's harder to read otherwise.

### 📄 Which files need to be modified?

The file that needs to be modified is **README.md**

### 📚 Resources
- [How to make sure your commits are formatted correctly](https://github.com/lirantal/express-security-txt/blob/master/README.md#contributing)
- Ask if you need help

**Comment by joker314** [comment]
@lirantal I'm going on holiday and am going to do my best to stay away from a computer. I've made this issue good for public contribution but feel free to fix this yourself, especially if you think that the poor wording might turn away potential users :)

Happy holidays!

**Comment by lirantal** [comment]
Oh sweet you should definitely take some time off and relax for the holidays ❤️ 
Thanks for opening this, I'll leave it out if anyone wants to take a stab at it.

Enjoy and have fun!

**Comment by joker314** [comment]
FYI - I'm back!

**Comment by lirantal** [comment]
![](https://media.giphy.com/media/l0IxYD16t9PDEdg9q/giphy.gif)
