### ISSUE TITLE
Directives removed: Signature, Permission - New directive: Canonical

### ISSUE THREAD

**Issue by joker314** [lirantal/express-security-txt#52]
See securitytxt/security-txt#140

We will need to discuss how to implement inline signatures in an intuitive way, though

**Comment by lirantal** [comment]
@joker314 feel free to merge and iterate as you need to. I will be a bit behind in the next few weeks and don't want to block you from moving ahead.

**Comment by joker314** [comment]
Hi @lirantal, that's absolutely fine.

If you want to allow me to merge without your review (which you don't have to), you wold need to disable the master branch protection.

**Comment by lirantal** [comment]
Done.

**Comment by joker314** [comment]
Filing a new issue for signing the file. I'll file a PR for the removed directives and the new directive (and merge it in after a few days of reviewing them).
