### ISSUE TITLE
Redirect from /security.txt to /.well-known/security.txt

### ISSUE THREAD

**Issue by joker314** [lirantal/express-security-txt#57]
Recently, securitytxt/security-txt#145 was merged. It made, among some others, the following change:

```diff
- or be used as a fall back
+ or be used as a fall back if the ".well-known" path cannot be used
```

Given that we *are* able to use `.well-known`, perhaps we should be issuing a 3xx redirection now if someone requests `/security.txt` rather than `/.well-known/security.txt`. Alternatively, we could allow people to pick which behaviour they would like to use.

**Comment by lirantal** [comment]
Well, right now we also don't allow anyone to change the routes, as they hard hard-coded in the middleware, so I think an internal redirection from `/security.txt` to `/.well-known/security.txt` would make sense.
